package nilquant

const MARKET_TYPE_TRADE = "trade"
const MARKET_TYPE_ORDERBOOK = "orderbook"
const MARKET_TYPE_KLINE = "kline"
const MARKET_TYPE_KLINE_3M = "kline_3m"
const MARKET_TYPE_KLINE_5M = "kline_5m"
const MARKET_TYPE_KLINE_15M = "kline_15m"
const MARKET_TYPE_KLINE_30M = "kline_30m"
const MARKET_TYPE_KLINE_1H = "kline_1h"
const MARKET_TYPE_KLINE_3H = "kline_3h"
const MARKET_TYPE_KLINE_6H = "kline_6h"
const MARKET_TYPE_KLINE_12H = "kline_12h"
const MARKET_TYPE_KLINE_1D = "kline_1d"
const MARKET_TYPE_KLINE_3D = "kline_3d"
const MARKET_TYPE_KLINE_1W = "kline_1w"
const MARKET_TYPE_KLINE_15D = "kline_15d"
const MARKET_TYPE_KLINE_1MON = "kline_1mon"
const MARKET_TYPE_KLINE_1Y = "kline_1y"
